import type { CoachClientSummary, CoachGoal, CoachNote, CoachingPrivacySettings } from '@tfk/types';
import Link from 'next/link';
import { saveCoachGoal, saveCoachNote, completeCoachGoal, archiveCoachGoal, updateCoachGoal, updateCoachingPrivacy } from '../../server/actions/coaching';
import { SubmitButton } from '../../components/forms/submit-button';
import { Card, CardContent, CardHeader } from '../../components/ui/card';
import { FormField, Input, Select } from '../../components/ui/form';

export function coachingScore(client:CoachClientSummary) {
  const n=client.nutrition; const a=client.accountability;
  const nutrition=n?Math.round(((n.logged_days_7d+n.protein_days_7d)/14)*30):0;
  const hydration=n?Math.round((n.water_days_7d/7)*15):0;
  const habits=a?Math.round((a.habit_completion_pct/100)*30):0;
  const checkIns=a?Math.round((a.check_in_days_7d/7)*15):0;
  const progress=client.progress?.last_weigh_in&&Date.now()-new Date(client.progress.last_weigh_in).getTime()<7*864e5?10:0;
  const overall=Math.min(100,nutrition+hydration+habits+checkIns+progress);
  return {overall,breakdown:{nutrition,hydration,habits,checkIns,progress}};
}
export function attentionLabel(client:CoachClientSummary) { const score=coachingScore(client).overall;if(!client.accountability?.last_check_in||Date.now()-new Date(client.accountability.last_check_in).getTime()>3*864e5)return 'Check-in overdue';if(score<60)return 'Low recent consistency';if(!client.progress?.last_weigh_in||Date.now()-new Date(client.progress.last_weigh_in).getTime()>7*864e5)return 'Needs review';return 'On track'; }
const displayWeight=(value:number|null|undefined,imperial:boolean)=>value==null?'—':`${(imperial?value*2.20462:value).toFixed(1)} ${imperial?'lb':'kg'}`;
export function CoachClientCard({client}:{client:CoachClientSummary}) {const score=coachingScore(client);const imperial=client.unit_system==='imperial';return <Card><CardHeader title={client.display_name} description={attentionLabel(client)} action={<span className="rounded-full bg-muted px-3 py-1 text-xs font-bold">TFK {score.overall}</span>}/><CardContent className="grid gap-3 text-sm"><p><strong>Weight:</strong> {displayWeight(client.progress?.latest_weight,imperial)} / {displayWeight(client.goal?.goal_weight,imperial)}</p><p><strong>7-day logging:</strong> {client.nutrition?.logged_days_7d??0}/7 nutrition days · {client.accountability?.check_in_days_7d??0}/7 check-ins</p><p><strong>Last weigh-in:</strong> {client.progress?.last_weigh_in?new Intl.DateTimeFormat('en',{dateStyle:'medium',timeZone:client.timezone}).format(new Date(client.progress.last_weigh_in)):'Not recorded'}</p><Link className="font-semibold text-primary" href={`/coach/clients/${client.client_id}`}>Review client</Link></CardContent></Card>}

export function CoachGoalForm({clientId}:{clientId:string}) {return <Card><CardHeader title="Add coaching goal" description="Set one clear, action-oriented focus."/><CardContent><form action={saveCoachGoal} className="grid gap-4"><input type="hidden" name="client_id" value={clientId}/><FormField id="title" label="Goal"><Input id="title" name="title" required maxLength={120}/></FormField><FormField id="description" label="Description"><Input id="description" name="description" maxLength={1000}/></FormField><div className="grid gap-4 sm:grid-cols-3"><FormField id="category" label="Category"><Select id="category" name="category">{['nutrition','hydration','movement','sleep','mindset','progress','accountability','custom'].map(x=><option key={x}>{x}</option>)}</Select></FormField><FormField id="priority" label="Priority"><Select id="priority" name="priority"><option>normal</option><option>high</option><option>low</option></Select></FormField><FormField id="target_date" label="Target date"><Input id="target_date" name="target_date" type="date"/></FormField></div><label className="flex gap-2 text-sm"><input type="checkbox" name="client_visible" defaultChecked/>Visible to client</label><SubmitButton pendingLabel="Saving…">Save goal</SubmitButton></form></CardContent></Card>}
export function GoalList({goals,coach=false}:{goals:CoachGoal[];coach?:boolean}) {return <Card><CardHeader title="Coach goals"/><CardContent className="grid gap-3">{goals.length?goals.map(g=><article key={g.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-center gap-2"><strong>{g.title}</strong><span className="rounded bg-muted px-2 py-1 text-xs">{g.status}</span><span className="rounded bg-muted px-2 py-1 text-xs">{g.priority}</span></div>{g.description?<p className="mt-2 text-sm text-muted-foreground">{g.description}</p>:null}{g.target_date?<p className="mt-2 text-xs">Target: {g.target_date}</p>:null}{coach&&g.status==='active'?<><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-primary">Edit goal</summary><form action={updateCoachGoal} className="mt-3 grid gap-3"><input type="hidden" name="goal_id" value={g.id}/><input type="hidden" name="client_id" value={g.client_user_id}/><Input name="title" defaultValue={g.title} required/><Input name="description" defaultValue={g.description??''}/><div className="grid gap-3 sm:grid-cols-3"><Select name="category" defaultValue={g.category}>{['nutrition','hydration','movement','sleep','mindset','progress','accountability','custom'].map(x=><option key={x}>{x}</option>)}</Select><Select name="priority" defaultValue={g.priority}><option>normal</option><option>high</option><option>low</option></Select><Input name="target_date" type="date" defaultValue={g.target_date??''}/></div><label className="flex gap-2 text-sm"><input type="checkbox" name="client_visible" defaultChecked={g.client_visible}/>Visible to client</label><SubmitButton size="sm" pendingLabel="Updating…">Update goal</SubmitButton></form></details><div className="mt-3 flex gap-2"><form action={completeCoachGoal}><input type="hidden" name="goal_id" value={g.id}/><input type="hidden" name="client_id" value={g.client_user_id}/><SubmitButton size="sm" pendingLabel="Completing…">Complete</SubmitButton></form><form action={archiveCoachGoal}><input type="hidden" name="goal_id" value={g.id}/><input type="hidden" name="client_id" value={g.client_user_id}/><SubmitButton size="sm" variant="outline" pendingLabel="Archiving…">Archive</SubmitButton></form></div></>:null}</article>):<p className="text-sm text-muted-foreground">No coaching goals yet.</p>}</CardContent></Card>}
export function CoachNotePanel({clientId,notes}:{clientId:string;notes:CoachNote[]}) {return <Card><CardHeader title="Coach notes" description="Notes are private unless you explicitly share them."/><CardContent className="grid gap-5"><form action={saveCoachNote} className="grid gap-3"><input type="hidden" name="client_id" value={clientId}/><FormField id="note" label="Add note"><Input id="note" name="note" required maxLength={2000}/></FormField><label className="flex gap-2 text-sm"><input type="checkbox" name="client_visible"/>Visible to client</label><SubmitButton pendingLabel="Saving…">Save note</SubmitButton></form>{notes.map(n=><article key={n.id} className="rounded-lg border p-3 text-sm"><span className="rounded bg-muted px-2 py-1 text-xs">{n.client_visible?'Client visible':'Private'}</span><p className="mt-2">{n.note}</p></article>)}</CardContent></Card>}
export function PrivacyForm({privacy}:{privacy:CoachingPrivacySettings|null}) {const item=(name:string,label:string,checked:boolean)=><label className="flex items-center gap-3 text-sm"><input type="checkbox" name={name} defaultChecked={checked}/>{label}</label>;return <Card><CardHeader title="Sharing controls" description="Choose which bounded summaries your assigned coach can review. GLP-1 sharing is off by default."/><CardContent><form action={updateCoachingPrivacy} className="grid gap-4">{item('share_progress','Progress summary',privacy?.share_progress??true)}{item('share_nutrition','Nutrition adherence summary',privacy?.share_nutrition??true)}{item('share_accountability','Habits and check-in summary',privacy?.share_accountability??true)}{item('share_glp1_summary','GLP-1 journal summary',privacy?.share_glp1_summary??false)}<SubmitButton pendingLabel="Updating…">Update sharing</SubmitButton></form></CardContent></Card>}
