begin;
set local search_path=public,extensions;
select plan(9);
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data) values('a1533333-3333-4333-8333-333333333333','authenticated','authenticated','replay-sql@local.test','{}','{}');
insert into public.user_subscriptions(user_id,plan_id,status,provider) select 'a1533333-3333-4333-8333-333333333333',id,'active','internal' from public.plans where code='premium';
set local role authenticated;
select set_config('request.jwt.claim.sub','a1533333-3333-4333-8333-333333333333',true);
select set_config('test.key',floor(extract(epoch from clock_timestamp())*1000)::text||':'||gen_random_uuid()::text,true);
select set_config('test.food',jsonb_build_object('meal_type','lunch','food_name_snapshot','Rice','servings',1,'serving_size_snapshot',1,'serving_unit_snapshot','serving','calories',200,'protein_g',4,'carbs_g',45,'fat_g',1,'logged_at','2026-09-15T12:00:00Z')::text,true);
select lives_ok($$select public.replay_safe_mutation(current_setting('test.key'),'food_log',current_setting('test.food')::jsonb)$$,'Food creation accepted');
select lives_ok($$select public.replay_safe_mutation(current_setting('test.key'),'food_log',current_setting('test.food')::jsonb)$$,'Food replay accepted');
select is((select count(*)::int from public.food_logs),1,'Replay creates one food snapshot');
select throws_ok($$select public.replay_safe_mutation(current_setting('test.key'),'food_log',current_setting('test.food')::jsonb||'{"calories":201}')$$,'22023',null,'Changed input rejected');
select set_config('test.exercise',public.training_mutate('save_exercise','{"name":"Replay squat","category":"strength","equipment":"none","tracking_type":"bodyweight"}')->>'id',true);
select set_config('test.template',public.training_mutate('save_template',jsonb_build_object('name','Replay workout','items',jsonb_build_array(jsonb_build_object('exercise_id',current_setting('test.exercise'),'target_sets',1,'target_reps_min',1))))->>'id',true);
select set_config('test.key',floor(extract(epoch from clock_timestamp())*1000)::text||':'||gen_random_uuid()::text,true);
select set_config('test.session',public.replay_safe_mutation(current_setting('test.key'),'training_start',jsonb_build_object('workout_template_id',current_setting('test.template')))->>'id',true);
select is(public.replay_safe_mutation(current_setting('test.key'),'training_start',jsonb_build_object('workout_template_id',current_setting('test.template')))->>'id',current_setting('test.session'),'Workout replay reuses original result');
select is((select count(*)::int from public.workout_sessions),1,'One self-directed workout');
select lives_ok($$select public.replay_safe_mutation(floor(extract(epoch from clock_timestamp())*1000)::text||':'||gen_random_uuid()::text,'training_start',jsonb_build_object('workout_template_id',current_setting('test.template')))$$,'Distinct workout key creates legitimate session');
select is((select count(*)::int from public.workout_sessions),2,'Distinct workout not collapsed');
select throws_ok($$select public.replay_safe_mutation('1000000000000:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','food_log',current_setting('test.food')::jsonb)$$,'22023',null,'Expired receipt cannot replay after pruning');
select * from finish();rollback;
