begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions,auth;
select no_plan();
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select '00000000-0000-0000-0000-000000000000',id::uuid,'authenticated','authenticated',name||'@training.example.test','',now(),'{}','{}',now(),now()
from (values
('91111111-1111-4111-8111-111111111111','client-a'),('92222222-2222-4222-8222-222222222222','client-b'),
('93333333-3333-4333-8333-333333333333','coach-a'),('94444444-4444-4444-8444-444444444444','coach-b'),
('95555555-5555-4555-8555-555555555555','free'),('96666666-6666-4666-8666-666666666666','admin'))u(id,name);
update public.user_roles set role='coach' where user_id in ('93333333-3333-4333-8333-333333333333','94444444-4444-4444-8444-444444444444');
update public.user_roles set role='admin' where user_id='96666666-6666-4666-8666-666666666666';
insert into public.user_subscriptions(user_id,plan_id,status,provider)
select u.id::uuid,p.id,'active','internal' from (values('91111111-1111-4111-8111-111111111111','premium'),('92222222-2222-4222-8222-222222222222','premium'),('93333333-3333-4333-8333-333333333333','coach'),('94444444-4444-4444-8444-444444444444','coach'))u(id,code) join public.plans p on p.code=u.code;
insert into public.coach_client_relationships(coach_user_id,client_user_id,status) values('93333333-3333-4333-8333-333333333333','91111111-1111-4111-8111-111111111111','active');
select is((select count(*)::int from pg_tables where schemaname='public' and tablename in ('exercises','workout_templates','workout_template_items','training_programs','training_program_workouts','workout_assignments','workout_sessions','workout_session_exercises','workout_set_logs') and rowsecurity),9,'All training tables have RLS');
set local role anon;
select throws_ok($$select * from public.exercises$$,'42501',null,'Anon cannot read training');
select throws_ok($$select public.training_mutate('save_exercise','{}')$$,'42501',null,'Anon cannot execute training commands');
set local role authenticated;
select set_config('request.jwt.claim.sub','95555555-5555-4555-8555-555555555555',true);
select throws_ok($$select public.training_mutate('save_exercise','{}')$$,'42501',null,'Free user cannot mutate training');
select throws_ok($$select public.get_training_summary()$$,'42501',null,'Free user cannot get summary');
select is((select count(*)::int from public.workout_sessions),0,'Free user cannot read sessions');
select set_config('request.jwt.claim.sub','91111111-1111-4111-8111-111111111111',true);
select ok((select count(*) from public.exercises where owner_user_id is null)>=10,'Starter exercise library readable');
select throws_ok($$update public.exercises set name='Forged system' where owner_user_id is null$$,'42501',null,'System exercise direct update denied');
select throws_ok($$select public.training_mutate('save_exercise',jsonb_build_object('id',(select id from public.exercises where owner_user_id is null limit 1),'name','Forged','category','strength','equipment','none','tracking_type','bodyweight'))$$,'42501',null,'System exercise RPC update denied');
select set_config('test.exercise',public.training_mutate('save_exercise','{"name":"Custom squat","category":"strength","equipment":"dumbbell","tracking_type":"sets_reps"}')->>'id',true);
select is((select owner_user_id from public.exercises where id=current_setting('test.exercise')::uuid),auth.uid(),'Exercise owner derived from auth');
select throws_ok($$select public.training_mutate('save_exercise','{"owner_user_id":"92222222-2222-4222-8222-222222222222","name":"Forged"}')$$,'42501',null,'Caller owner rejected');
select set_config('test.template',public.training_mutate('save_template',jsonb_build_object('name','My workout','items',jsonb_build_array(jsonb_build_object('exercise_id',current_setting('test.exercise'),'target_sets',3,'target_reps_min',8))))->>'id',true);
select is((select count(*)::int from public.workout_template_items),1,'Owned template item created');
select throws_ok($$insert into public.workout_templates(owner_user_id,name) values(auth.uid(),'Bypass')$$,'42501',null,'Direct template writes denied');
select set_config('test.program',public.training_mutate('save_program',jsonb_build_object('name','Basic program','duration_weeks',4,'workouts',jsonb_build_array(jsonb_build_object('workout_template_id',current_setting('test.template'),'week_number',1,'day_number',1))))->>'id',true);
select is((select count(*)::int from public.training_program_workouts),1,'Owned program stores ordered workout');
select set_config('test.self_assignment',public.training_mutate('assign',jsonb_build_object('workout_template_id',current_setting('test.template'),'assigned_for',current_date))->>'id',true);
select is((select coach_user_id from public.workout_assignments where id=current_setting('test.self_assignment')::uuid),null::uuid,'Self assignment has no forged coach');
select set_config('test.session',public.training_mutate('start',jsonb_build_object('assignment_id',current_setting('test.self_assignment')))->>'id',true);
select is(public.training_mutate('start',jsonb_build_object('assignment_id',current_setting('test.self_assignment')))->>'id',current_setting('test.session'),'Repeated start resumes same assigned session');
select set_config('test.session_exercise',(select id::text from public.workout_session_exercises where workout_session_id=current_setting('test.session')::uuid limit 1),true);
select throws_ok($$select public.training_mutate('complete',jsonb_build_object('id',current_setting('test.session')))$$,'22023',null,'Empty session completion rejected');
select is((select status from public.workout_assignments where id=current_setting('test.self_assignment')::uuid),'in_progress','Failed completion leaves assignment in progress');
select throws_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.session_exercise'),'set_number',1,'reps',8,'rpe',11))$$,'23514',null,'Invalid RPE rejected by database');
select throws_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.session_exercise'),'set_number',1,'duration_seconds',60))$$,'22023',null,'Strength requires reps');
select lives_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.session_exercise'),'set_number',1,'reps',8,'weight_kg',20,'rpe',7))$$,'User saves strength set');
select lives_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.session_exercise'),'set_number',1,'reps',10,'weight_kg',20))$$,'Set save is idempotent by set number');
select is((select count(*)::int from public.workout_set_logs),1,'Repeated save does not duplicate set');
select lives_ok($$select public.training_mutate('save_template',jsonb_build_object('id',current_setting('test.template'),'name','Renamed workout','items',jsonb_build_array(jsonb_build_object('exercise_id',current_setting('test.exercise')))))$$,'Owner edits template');
select is((select name_snapshot from public.workout_sessions where id=current_setting('test.session')::uuid),'My workout','Workout name snapshot survives template edit');
select lives_ok($$select public.training_mutate('save_exercise',jsonb_build_object('id',current_setting('test.exercise'),'name','Renamed exercise','category','strength','equipment','dumbbell','tracking_type','sets_reps'))$$,'Owner edits custom exercise');
select is((select exercise_name_snapshot from public.workout_session_exercises where id=current_setting('test.session_exercise')::uuid),'Custom squat','Exercise snapshot survives source edit');
select lives_ok($$select public.training_mutate('complete',jsonb_build_object('id',current_setting('test.session')))$$,'Atomic completion succeeds');
select is((select status from public.workout_assignments where id=current_setting('test.self_assignment')::uuid),'completed','Linked assignment completed');
select is((select completed_at from public.workout_assignments where id=current_setting('test.self_assignment')::uuid),(select completed_at from public.workout_sessions where id=current_setting('test.session')::uuid),'Completion timestamps identical');
select lives_ok($$select public.training_mutate('complete',jsonb_build_object('id',current_setting('test.session')))$$,'Completion retry is idempotent');
select throws_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.session_exercise'),'set_number',2,'reps',8))$$,'22023',null,'Completed session is read only');
select is((public.get_training_summary()->>'completed_7d')::int,1,'Deterministic seven-day completion summary');
select set_config('request.jwt.claim.sub','92222222-2222-4222-8222-222222222222',true);
select is((select count(*)::int from public.exercises where id=current_setting('test.exercise')::uuid),0,'Other custom exercises hidden');
select is((select count(*)::int from public.workout_templates),0,'Other user templates hidden');
select is((select count(*)::int from public.training_programs),0,'Other user programs hidden');
select is((select count(*)::int from public.workout_sessions),0,'Other sessions hidden');
select is((select count(*)::int from public.workout_session_exercises),0,'Other session exercises hidden');
select is((select count(*)::int from public.workout_set_logs),0,'Other set logs hidden');
select throws_ok($$select public.training_mutate('delete_exercise',jsonb_build_object('id',current_setting('test.exercise')))$$,'42501',null,'Other exercise delete denied');
select throws_ok($$select public.training_mutate('archive_template',jsonb_build_object('id',current_setting('test.template')))$$,'42501',null,'Other template archive denied');
select throws_ok($$select public.training_mutate('start',jsonb_build_object('workout_template_id',current_setting('test.template')))$$,'42501',null,'Other template execution denied');
select throws_ok($$select public.training_mutate('complete',jsonb_build_object('id',current_setting('test.session')))$$,'42501',null,'Other session completion denied');
select throws_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.session_exercise'),'set_number',2,'reps',8))$$,'42501',null,'Other session set mutation denied');
select set_config('request.jwt.claim.sub','93333333-3333-4333-8333-333333333333',true);
select throws_ok($$select public.training_mutate('delete_exercise',jsonb_build_object('id',current_setting('test.exercise')))$$,'42501',null,'Coach cannot edit client custom exercise');
select set_config('test.coach_template',public.training_mutate('save_template',jsonb_build_object('name','Coach plan','items',jsonb_build_array(jsonb_build_object('exercise_id',(select id from public.exercises where name='Walking' and owner_user_id is null limit 1)))))->>'id',true);
select throws_ok($$select public.training_mutate('assign',jsonb_build_object('workout_template_id',current_setting('test.coach_template'),'client_id','92222222-2222-4222-8222-222222222222'))$$,'42501',null,'Coach cannot assign to unassigned client');
select set_config('test.coach_assignment',public.training_mutate('assign',jsonb_build_object('workout_template_id',current_setting('test.coach_template'),'client_id','91111111-1111-4111-8111-111111111111','assigned_for',current_date))->>'id',true);
select is((select coach_user_id from public.workout_assignments where id=current_setting('test.coach_assignment')::uuid),auth.uid(),'Coach identity derived from auth');
select is((select count(*)::int from public.workout_set_logs),0,'Coach cannot read client raw sets');
select is((select count(*)::int from public.workout_sessions),0,'Coach cannot read client raw sessions');
select lives_ok($$select public.get_coach_client_training_summary('91111111-1111-4111-8111-111111111111')$$,'Assigned coach reads bounded summary');
select is((public.get_coach_client_training_summary('91111111-1111-4111-8111-111111111111')->>'completed_7d')::int,0,'Summary excludes unrelated self-directed training');
select set_config('request.jwt.claim.sub','94444444-4444-4444-8444-444444444444',true);
select throws_ok($$select public.training_mutate('assignment_status',jsonb_build_object('id',current_setting('test.coach_assignment'),'status','archived'))$$,'42501',null,'Other coach cannot mutate assignment');
select throws_ok($$select public.get_coach_client_training_summary('91111111-1111-4111-8111-111111111111')$$,'42501',null,'Unassigned coach summary denied');
select throws_ok($$select public.training_mutate('archive_template',jsonb_build_object('id',current_setting('test.coach_template')))$$,'42501',null,'Other coach cannot edit template');
select set_config('request.jwt.claim.sub','91111111-1111-4111-8111-111111111111',true);
select is((select count(*)::int from public.workout_templates where id=current_setting('test.coach_template')::uuid),1,'Client reads assigned template');
select throws_ok($$select public.training_mutate('assign',jsonb_build_object('workout_template_id',current_setting('test.coach_template'),'client_id','92222222-2222-4222-8222-222222222222'))$$,'42501',null,'Client cannot reassign coach template');
select throws_ok($$select public.training_mutate('assignment_status',jsonb_build_object('id',current_setting('test.coach_assignment'),'coach_user_id','94444444-4444-4444-8444-444444444444','status','assigned'))$$,'42501',null,'Client cannot forge coach identity');
select throws_ok($$select public.training_mutate('assignment_status',jsonb_build_object('id',current_setting('test.coach_assignment'),'status','completed'))$$,'22023',null,'Client cannot fabricate completed assignment');
select set_config('test.coach_session',public.training_mutate('start',jsonb_build_object('assignment_id',current_setting('test.coach_assignment')))->>'id',true);
select set_config('test.cardio_exercise',(select id::text from public.workout_session_exercises where workout_session_id=current_setting('test.coach_session')::uuid limit 1),true);
select throws_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.cardio_exercise'),'set_number',1,'duration_seconds',60))$$,'22023',null,'Cardio requires distance and duration');
select lives_ok($$select public.training_mutate('save_set',jsonb_build_object('session_exercise_id',current_setting('test.cardio_exercise'),'set_number',1,'duration_seconds',600,'distance_meters',800))$$,'Client logs assigned cardio');
select lives_ok($$select public.training_mutate('complete',jsonb_build_object('id',current_setting('test.coach_session')))$$,'Client completes coach assignment');
select set_config('request.jwt.claim.sub','93333333-3333-4333-8333-333333333333',true);
select is((public.get_coach_client_training_summary('91111111-1111-4111-8111-111111111111')->>'completed_7d')::int,1,'Coach sees assigned completion');
select is((public.get_coach_client_training_summary('91111111-1111-4111-8111-111111111111')->>'assigned_completed_7d')::int,1,'Coach adherence reflects completion');
reset role;
update public.coach_client_relationships set status='paused' where coach_user_id='93333333-3333-4333-8333-333333333333';
set local role authenticated;
select throws_ok($$select public.get_coach_client_training_summary('91111111-1111-4111-8111-111111111111')$$,'42501',null,'Paused relationship revokes summary');
select throws_ok($$select public.training_mutate('assign',jsonb_build_object('workout_template_id',current_setting('test.coach_template'),'client_id','91111111-1111-4111-8111-111111111111'))$$,'42501',null,'Paused relationship revokes assignment');
select set_config('request.jwt.claim.sub','91111111-1111-4111-8111-111111111111',true);
select is((select count(*)::int from public.workout_templates where id=current_setting('test.coach_template')::uuid),0,'Paused relationship hides coach template');
select is((select name_snapshot from public.workout_sessions where id=current_setting('test.coach_session')::uuid),'Coach plan','Client retains own history after relationship pauses');
select * from finish();
rollback;
