'use client';
import { useFormState } from 'react-dom';
import type { ReminderPreferences } from '@tfk/types';
import { saveReminderPreferences,changeNotificationReadState } from '../../server/actions/notifications';
import { FormField,Input,Select } from '../../components/ui/form';
import { SubmitButton } from '../../components/forms/submit-button';
import { Alert } from '../../components/ui/alert';
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export function ReminderSettingsForm({preferences:p}:{preferences:ReminderPreferences}){
 const [state,action]=useFormState(saveReminderPreferences,{});
 const toggle=(key:keyof ReminderPreferences,label:string)=><label className="flex items-center gap-3 font-semibold"><input type="checkbox" name={key} defaultChecked={Boolean(p[key])} className="size-5 accent-primary"/>{label}</label>;
 const time=(key:keyof ReminderPreferences,label:string)=><FormField id={key} label={label}><Input id={key} name={key} type="time" required defaultValue={String(p[key])}/></FormField>;
 return <form action={action} className="grid gap-6">{state.error?<Alert variant="error">{state.error}</Alert>:null}{state.message?<p role="status" className="text-sm font-semibold">{state.message}</p>:null}
 <fieldset className="grid gap-4 rounded-xl border p-5"><legend className="px-2 text-lg font-bold">Progress</legend>{toggle('weigh_in_enabled','Weigh-in reminders')}{time('weigh_in_time','Weigh-in time')}<fieldset><legend className="mb-2 text-sm font-semibold">Weigh-in days (choose at least one)</legend><div className="flex flex-wrap gap-4">{weekdays.map((day,i)=><label key={day} className="flex items-center gap-2 text-sm"><input type="checkbox" name="weigh_in_days_of_week" value={i} defaultChecked={p.weigh_in_days_of_week.includes(i)} className="size-4 accent-primary"/>{day}</label>)}</div></fieldset></fieldset>
 <fieldset className="grid gap-4 rounded-xl border p-5"><legend className="px-2 text-lg font-bold">Check-ins</legend>{toggle('daily_check_in_enabled','Daily check-in reminders')}{time('daily_check_in_time','Daily check-in time')}{toggle('weekly_check_in_enabled','Weekly check-in reminders')}<FormField id="weekly_check_in_day" label="Weekly check-in day"><Select id="weekly_check_in_day" name="weekly_check_in_day" defaultValue={p.weekly_check_in_day}>{weekdays.map((day,i)=><option key={day} value={i}>{day}</option>)}</Select></FormField>{time('weekly_check_in_time','Weekly check-in time')}</fieldset>
 <fieldset className="grid gap-4 rounded-xl border p-5"><legend className="px-2 text-lg font-bold">Habits</legend>{toggle('habit_reminders_enabled','One reminder for incomplete active habits')}{time('habit_reminder_time','Habit reminder time')}<p className="text-sm text-muted-foreground">Weekly habits stop prompting once their current week target is reached. Completed and inactive habits are excluded.</p></fieldset>
 <fieldset className="grid gap-4 rounded-xl border p-5"><legend className="px-2 text-lg font-bold">Training</legend>{toggle('workout_reminders_enabled','Assigned workout reminders')}<FormField id="workout_reminder_minutes_before" label="Minutes before the workout" hint="From 0 to 1,440 minutes (24 hours)."><Input id="workout_reminder_minutes_before" name="workout_reminder_minutes_before" type="number" min={0} max={1440} required defaultValue={p.workout_reminder_minutes_before}/></FormField>{time('workout_reminder_time','Workout time when only a date is assigned')}<p className="text-sm text-muted-foreground">A workout’s due time takes priority. Each assignment gets at most one reminder. Workouts already started or completed are excluded.</p></fieldset>
 <fieldset className="grid gap-4 rounded-xl border p-5"><legend className="px-2 text-lg font-bold">GLP-1 Journal</legend>{toggle('glp1_journal_enabled','Optional journal reminder')}{time('glp1_journal_time','Journal reminder time')}<p className="text-sm text-muted-foreground">“Remember to update your GLP-1 journal.” This is a tracking reminder only. It does not schedule or recommend medication.</p></fieldset>
 <fieldset className="grid gap-4 rounded-xl border p-5"><legend className="px-2 text-lg font-bold">Quiet Hours</legend>{toggle('quiet_hours_enabled','Pause reminders during quiet hours')}{time('quiet_hours_start','Quiet hours start')}{time('quiet_hours_end','Quiet hours end')}<p className="text-sm text-muted-foreground">Overnight ranges are supported. After quiet hours, only reminders still relevant to the current day or week may appear. Missed past days are not backfilled.</p></fieldset>
 <p className="text-sm text-muted-foreground">Reminders follow your current plan’s feature access. Saving enables these in-app preferences. Nothing is sent by email or push.</p><SubmitButton pendingLabel="Saving…" className="w-fit">Save reminder preferences</SubmitButton>
 </form>;
}
export function NotificationReadForm({id,read,all=false}:{id?:string;read?:boolean;all?:boolean}){
 const [state,action]=useFormState(changeNotificationReadState,{});
 return <form action={action} className="grid gap-2"><input type="hidden" name="operation" value={all?'all':'one'}/><input type="hidden" name="id" value={id??''}/><input type="hidden" name="read" value={String(read??true)}/><SubmitButton variant="outline" size="sm" pendingLabel="Updating…">{all?'Mark all read':read?'Mark read':'Mark unread'}</SubmitButton>{state.error?<p role="alert" className="text-sm text-destructive">{state.error}</p>:null}{state.message?<span role="status" className="sr-only">{state.message}</span>:null}</form>;
}
