import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('forgot-password targets the dedicated recovery callback',async()=>{const actions=await readFile(new URL('../server/actions/auth.ts',import.meta.url),'utf8');assert.match(actions,/redirectTo: `\$\{getAppOrigin\(\)\}\/auth\/recovery-callback`/);assert.doesNotMatch(actions,/auth\/callback\?next=\/reset-password/);});
test('recovery callback exchanges the PKCE code, sets the marker, and always succeeds to reset-password',async()=>{const callback=await readFile(new URL('../app/auth/recovery-callback/route.ts',import.meta.url),'utf8');assert.match(callback,/searchParams\.get\('code'\)/);assert.match(callback,/exchangeCodeForSession\(code\)/);assert.match(callback,/NextResponse\.redirect\(new URL\('\/reset-password'/);assert.match(callback,/tfk_recovery[\s\S]*httpOnly: true[\s\S]*maxAge: 600/);assert.doesNotMatch(callback,/dashboard|\/login/);});
test('missing or invalid recovery codes fail safely',async()=>{const callback=await readFile(new URL('../app/auth/recovery-callback/route.ts',import.meta.url),'utf8');assert.match(callback,/if \(!code\).*RECOVERY_ERROR/);assert.match(callback,/if \(error\).*RECOVERY_ERROR/);assert.match(callback,/Recovery%20link%20is%20invalid%20or%20expired/);});
test('normal callback keeps safe confirmation routing and never grants recovery access',async()=>{const callback=await readFile(new URL('../app/auth/callback/route.ts',import.meta.url),'utf8');assert.match(callback,/next\?\.startsWith\('\/'\)/);assert.match(callback,/: '\/dashboard'/);assert.match(callback,/exchangeCodeForSession/);assert.doesNotMatch(callback,/tfk_recovery|reset-password/);});
test('password update requires recovery marker and verified user',async()=>{const actions=await readFile(new URL('../server/actions/auth.ts',import.meta.url),'utf8');assert.match(actions,/updateRecoveredPassword[\s\S]*tfk_recovery[\s\S]*requireUser\(supabase\)[\s\S]*auth\.updateUser\(\{ password:/);assert.match(actions,/delete\('tfk_recovery'\)/);assert.doesNotMatch(actions,/service_role|console\.log\([^)]*password/);});
test('reset-password page requires recovery marker and authenticated session',async()=>{const page=await readFile(new URL('../app/reset-password/page.tsx',import.meta.url),'utf8');assert.match(page,/tfk_recovery/);assert.match(page,/requireUser\(createClient\(\)\)/);assert.match(page,/Saving…/);assert.match(page,/searchParams\.error/);});
