'use server';

import { calculateFoodSnapshot, zonedDateTimeToIso } from '@tfk/api';
import type { Food, FoodLog } from '@tfk/types';
import { foodLogSchema, foodSchema, quickAddSchema, savedMealDetailsSchema, savedMealSchema, updateFoodLogSchema, waterLogSchema, waterToMilliliters } from '@tfk/validation';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient } from '../../lib/data/client';
import { requireUser } from '../../lib/data/session';
import { formValue, redirectWithError } from './form';

const pathFor=(data:FormData)=>`/nutrition?date=${encodeURIComponent(formValue(data,'date'))}`;
const finish=(data:FormData,message:string)=>{revalidatePath('/nutrition');revalidatePath('/dashboard');redirect(`${pathFor(data)}&message=${encodeURIComponent(message)}`);};
const fail=(data:FormData,message:string):never=>redirectWithError(pathFor(data),message);
const loggedAt=(data:FormData,value:string)=>zonedDateTimeToIso(value,formValue(data,'timezone')||'UTC');

export async function createFood(data:FormData){const parsed=foodSchema.safeParse(Object.fromEntries(['name','brand','serving_size','serving_unit','calories','protein_g','carbs_g','fat_g','fiber_g'].map((key)=>[key,formValue(data,key)])));if(!parsed.success)fail(data,parsed.error.issues[0]?.message??'Invalid food.');const supabase=createClient();const user=await requireUser(supabase);const input=parsed.data!;const {error}=await supabase.from('foods').insert({owner_user_id:user.id,source:'manual',...input,brand:input.brand||null,fiber_g:input.fiber_g===''?null:input.fiber_g});if(error)fail(data,'Food could not be saved.');finish(data,'Food saved.');}
export async function logFood(data:FormData){const parsed=foodLogSchema.safeParse({food_id:formValue(data,'food_id'),meal_type:formValue(data,'meal_type'),servings:formValue(data,'servings'),logged_at:formValue(data,'logged_at'),notes:formValue(data,'notes')});if(!parsed.success)fail(data,parsed.error.issues[0]?.message??'Invalid food log.');const supabase=createClient();const user=await requireUser(supabase);const input=parsed.data!;const {data:food,error}=await supabase.from('foods').select('*').eq('id',input.food_id).single();if(error||!food)fail(data,'Food was not found.');const f=food as Food;const totals=calculateFoodSnapshot(f,input.servings);const result=await supabase.from('food_logs').insert({user_id:user.id,food_id:f.id,meal_type:input.meal_type,food_name_snapshot:f.name,brand_snapshot:f.brand,servings:input.servings,serving_size_snapshot:f.serving_size,serving_unit_snapshot:f.serving_unit,...totals,logged_at:loggedAt(data,input.logged_at),notes:input.notes||null});if(result.error)fail(data,'Food could not be logged.');finish(data,'Food logged.');}
export async function quickAddFood(data:FormData){const parsed=quickAddSchema.safeParse({name:formValue(data,'name'),meal_type:formValue(data,'meal_type'),calories:formValue(data,'calories'),protein_g:formValue(data,'protein_g')||0,carbs_g:formValue(data,'carbs_g')||0,fat_g:formValue(data,'fat_g')||0,logged_at:formValue(data,'logged_at'),notes:formValue(data,'notes')});if(!parsed.success)fail(data,parsed.error.issues[0]?.message??'Invalid quick add.');const supabase=createClient();const user=await requireUser(supabase);const input=parsed.data!;const {error}=await supabase.from('food_logs').insert({user_id:user.id,food_id:null,meal_type:input.meal_type,food_name_snapshot:input.name,servings:1,serving_size_snapshot:1,serving_unit_snapshot:'serving',calories:input.calories,protein_g:input.protein_g,carbs_g:input.carbs_g,fat_g:input.fat_g,logged_at:loggedAt(data,input.logged_at),notes:input.notes||null});if(error)fail(data,'Quick entry could not be logged.');finish(data,'Food logged.');}
export async function updateFoodLog(data:FormData){const parsed=updateFoodLogSchema.safeParse({id:formValue(data,'id'),meal_type:formValue(data,'meal_type'),servings:formValue(data,'servings'),logged_at:formValue(data,'logged_at'),notes:formValue(data,'notes')});if(!parsed.success)fail(data,parsed.error.issues[0]?.message??'Invalid update.');const supabase=createClient();await requireUser(supabase);const input=parsed.data!;const {data:row,error}=await supabase.from('food_logs').select('*').eq('id',input.id).single();if(error||!row)fail(data,'Food log was not found.');const log=row as FoodLog;const ratio=input.servings/log.servings;const {error:updateError}=await supabase.from('food_logs').update({meal_type:input.meal_type,servings:input.servings,calories:Number((log.calories*ratio).toFixed(2)),protein_g:Number((log.protein_g*ratio).toFixed(2)),carbs_g:Number((log.carbs_g*ratio).toFixed(2)),fat_g:Number((log.fat_g*ratio).toFixed(2)),fiber_g:log.fiber_g===null?null:Number((log.fiber_g*ratio).toFixed(2)),logged_at:loggedAt(data,input.logged_at),notes:input.notes||null}).eq('id',input.id);if(updateError)fail(data,'Food log could not be updated.');finish(data,'Food updated.');}
export async function deleteFoodLog(data:FormData){const supabase=createClient();await requireUser(supabase);const {error}=await supabase.from('food_logs').delete().eq('id',formValue(data,'id'));if(error)fail(data,'Food log could not be deleted.');finish(data,'Food deleted.');}
export async function toggleFavoriteFood(data:FormData){const supabase=createClient();await requireUser(supabase);const {error}=await supabase.from('foods').update({is_favorite:formValue(data,'favorite')!=='true'}).eq('id',formValue(data,'id'));if(error)fail(data,'Favorite could not be updated.');finish(data,'Favorite updated.');}
export async function createSavedMeal(data:FormData){const parsed=savedMealSchema.safeParse({name:formValue(data,'name'),description:formValue(data,'description'),food_ids:data.getAll('food_ids').map(String)});if(!parsed.success)fail(data,parsed.error.issues[0]?.message??'Invalid meal.');const supabase=createClient();const user=await requireUser(supabase);const input=parsed.data!;const {data:foods,error:foodError}=await supabase.from('foods').select('*').in('id',input.food_ids);if(foodError||!foods||foods.length!==input.food_ids.length)fail(data,'One or more foods could not be loaded.');const {data:meal,error}=await supabase.from('saved_meals').insert({user_id:user.id,name:input.name,description:input.description||null}).select('id').single();if(error||!meal)fail(data,'Meal could not be saved.');const mealId=meal!.id;const items=(foods as Food[]).map((food,index)=>({saved_meal_id:mealId,food_id:food.id,food_name_snapshot:food.name,servings:1,serving_size_snapshot:food.serving_size,serving_unit_snapshot:food.serving_unit,calories:food.calories,protein_g:food.protein_g,carbs_g:food.carbs_g,fat_g:food.fat_g,position:index}));const inserted=await supabase.from('saved_meal_items').insert(items);if(inserted.error){await supabase.from('saved_meals').delete().eq('id',mealId);fail(data,'Meal items could not be saved.');}finish(data,'Meal saved.');}
export async function logSavedMeal(data:FormData){const supabase=createClient();await requireUser(supabase);const {error}=await supabase.rpc('log_saved_meal',{p_saved_meal_id:formValue(data,'id'),p_meal_type:formValue(data,'meal_type') as 'breakfast',p_logged_at:loggedAt(data,formValue(data,'logged_at'))});if(error)fail(data,'Meal could not be logged.');finish(data,'Meal logged.');}
export async function updateSavedMeal(data:FormData){const parsed=savedMealDetailsSchema.safeParse({id:formValue(data,'id'),name:formValue(data,'name'),description:formValue(data,'description')});if(!parsed.success)fail(data,parsed.error.issues[0]?.message??'Invalid meal.');const supabase=createClient();await requireUser(supabase);const input=parsed.data!;const {error}=await supabase.from('saved_meals').update({name:input.name,description:input.description||null}).eq('id',input.id);if(error)fail(data,'Meal could not be updated.');finish(data,'Meal updated.');}
export async function deleteSavedMeal(data:FormData){const supabase=createClient();await requireUser(supabase);const {error}=await supabase.from('saved_meals').delete().eq('id',formValue(data,'id'));if(error)fail(data,'Meal could not be deleted.');finish(data,'Meal deleted.');}
export async function logWater(data:FormData){const parsed=waterLogSchema.safeParse({amount:formValue(data,'amount'),unit_system:formValue(data,'unit_system'),logged_at:formValue(data,'logged_at')});if(!parsed.success)fail(data,parsed.error.issues[0]?.message??'Invalid water amount.');const supabase=createClient();const user=await requireUser(supabase);const input=parsed.data!;const {error}=await supabase.from('water_logs').insert({user_id:user.id,amount_ml:waterToMilliliters(input.amount,input.unit_system),logged_at:loggedAt(data,input.logged_at)});if(error)fail(data,'Water could not be added.');finish(data,'Water added.');}
export async function deleteWaterLog(data:FormData){const supabase=createClient();await requireUser(supabase);const {error}=await supabase.from('water_logs').delete().eq('id',formValue(data,'id'));if(error)fail(data,'Water could not be deleted.');finish(data,'Water deleted.');}
