import Link from 'next/link';
import type { ReportAvailability, ReportContext, ReportPeriod, ReportPoint, TFKReport } from '@tfk/types';
import { Card, CardContent, CardHeader } from '../../components/ui/card';
import { Input, Select, FormField } from '../../components/ui/form';
import { buttonStyles } from '../../components/ui/button';
import { changeText } from './domain';

const show=(n:number|null,unit='')=>n===null?'Not available':n.toLocaleString('en-US',{maximumFractionDigits:2})+(unit?' '+unit:'');
const labels:Record<ReportAvailability,string>={available:'Recorded data',no_entries:'No entries in this period',not_applicable:'Not available for this account',not_shared:'Not shared'};
export function ReportFilters({context,period,path}:{context:ReportContext;period?:ReportPeriod;path:string}) {
 return <Card><CardContent className="grid gap-4 pt-5"><nav aria-label="Report periods" className="flex flex-wrap gap-2">{['7','30','90'].map(value=><Link key={value} href={path+'?preset='+value} aria-current={period?.preset===value?'page':undefined} className={buttonStyles({variant:period?.preset===value?'primary':'outline',size:'sm'})}>{value} days</Link>)}</nav><form action={path} className="grid gap-3 sm:grid-cols-4"><FormField id="report-preset" label="Period"><Select id="report-preset" name="preset" defaultValue="custom"><option value="custom">Custom dates</option></Select></FormField><FormField id="report-start" label="Start date"><Input id="report-start" name="start" type="date" min="1900-01-01" max={context.today} defaultValue={period?.start} required/></FormField><FormField id="report-end" label="End date"><Input id="report-end" name="end" type="date" min="1900-01-01" max={context.today} defaultValue={period?.end??context.today} required/></FormField><button className={buttonStyles({className:'self-end'})}>Apply range</button></form><p className="text-sm text-muted-foreground">Dates use {context.timezone}. Custom ranges support up to 365 inclusive days.</p></CardContent></Card>;
}
function Metrics({rows}:{rows:Array<[string,number|null,string?]>}){return <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(([name,value,unit])=><div key={name}><dt className="text-sm text-muted-foreground">{name}</dt><dd className="mt-1 text-lg font-bold">{show(value,unit)}</dd></div>)}</dl>;}
/** Same dependency-free SVG approach as Progress. Missing points break lines and
 * every plotted value has a table equivalent; neither color nor hover is required. */
export function ReportChart({points,title,unit}:{points:ReportPoint[];title:string;unit:string}){
 const known=points.filter(p=>p.value!==null);if(!known.length)return <p className="text-sm text-muted-foreground">No recorded values to plot for {title.toLowerCase()}.</p>;
 const low=Math.min(...known.map(p=>p.value!));const high=Math.max(...known.map(p=>p.value!));const range=Math.max(high-low,1);
 const xy=(p:ReportPoint,i:number)=>({x:45+i/Math.max(points.length-1,1)*610,y:155-(p.value!-low)/range*120});
 let path='';let prior=false;points.forEach((p,i)=>{if(p.value===null){prior=false;return;}const pos=xy(p,i);path+=(prior?' L':' M')+pos.x+','+pos.y;prior=true;});
 return <figure className="grid gap-2"><figcaption className="font-semibold">{title} ({unit})</figcaption><svg viewBox="0 0 700 195" role="img" aria-label={title+'; daily values and missing dates are listed in the table below.'} className="h-48 w-full"><text x="0" y="30" fontSize="12" fill="currentColor">{show(high)}</text><text x="0" y="158" fontSize="12" fill="currentColor">{show(low)}</text><line x1="45" y1="160" x2="660" y2="160" className="stroke-border"/><path d={path} fill="none" className="stroke-primary" strokeWidth="2"/>{points.map((p,i)=>p.value===null?null:<circle key={p.date} cx={xy(p,i).x} cy={xy(p,i).y} r="2.5" className="fill-primary"/>)}<text x="45" y="185" fontSize="12" fill="currentColor">{points[0]?.date}</text><text x="660" y="185" textAnchor="end" fontSize="12" fill="currentColor">{points.at(-1)?.date}</text></svg><p className="text-xs text-muted-foreground">{known.length} recorded dates. Range {show(low,unit)} to {show(high,unit)}. Gaps indicate missing values; lines connect adjacent recorded dates only.</p><details className="rounded-lg border p-3"><summary className="cursor-pointer rounded font-semibold focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-primary/20">View {title.toLowerCase()} values</summary><div className="max-h-64 overflow-auto"><table className="mt-3 w-full text-left text-sm"><caption className="sr-only">{title}: date and value in {unit}</caption><thead><tr><th scope="col">Local date</th><th scope="col">{unit}</th></tr></thead><tbody>{points.map(p=><tr key={p.date} className="border-t"><th scope="row" className="py-1 font-normal">{p.date}</th><td>{p.value===null?'No entry':show(p.value)}</td></tr>)}</tbody></table></div></details></figure>;
}
export function ReportSections({report:r}:{report:TFKReport}) {
 const {progress:p,nutrition:n,hydration:h,accountability:a,training:t}=r;
 return <>
 <Card><CardHeader title="Overview" description={r.period.start+' – '+r.period.end+' · '+r.period.days+' local days'+(r.period.includesToday?' · today is partial':'')}/><CardContent className="grid gap-5"><Metrics rows={[
 ['Canonical TFK Score',a.score?.overall??null,'/100'],['Weigh-ins',p.count],['Weight change',p.change,p.unit],['Nutrition logged',n.loggedDays,'days'],['Protein adherence on logged days',n.proteinPct,'%'],['Water target reached',h.targetDays,'days'],['Daily habit completion',a.habitPct,'%'],['Daily check-ins',a.checkInDays,'days'],['Completed workouts',t.completed],
 ]}/><p className="text-sm text-muted-foreground">Missing logs do not establish what happened offline. The TFK Score always covers seven days ending {a.scoreEnd}; it is not a score for the whole selected range. Withheld categories remain unavailable.</p></CardContent></Card>
 {r.comparison?<Card><CardHeader title="Previous equivalent period" description={r.comparison.start+' – '+r.comparison.end}/><CardContent><ul className="grid gap-2 text-sm"><li>Nutrition logging: {changeText(r.comparison.nutritionLoggedDays,'logged days')}</li><li>Canonical seven-day score: {changeText(r.comparison.scorePoints,'points')}</li><li>Workout completion: {changeText(r.comparison.workoutsCompleted,'workouts')}</li><li>Daily habit completion: {changeText(r.comparison.habitPercentagePoints,'percentage points')}</li></ul></CardContent></Card>:null}
 <Card><CardHeader title="Weight & Progress" description={labels[p.availability]}/><CardContent className="grid gap-5"><Metrics rows={[["First period weight",p.start,p.unit],["Last period weight",p.end,p.unit],["Change between period readings",p.change,p.unit],["Weigh-ins",p.count]]}/><p className="text-sm text-muted-foreground">Change requires at least two readings. The chart shows the last recorded weight on each date. No measurement outside the period is carried forward.</p><ReportChart points={p.trend} title="Weight" unit={p.unit}/></CardContent></Card>
 <Card><CardHeader title="Nutrition" description={labels[n.availability]}/><CardContent className="grid gap-5"><Metrics rows={[["Logged days",n.loggedDays],["Average calories on logged days",n.averageCalories,"kcal"],["Configured calorie target",n.calorieTarget,"kcal"],["Days within calorie tolerance",n.calorieDays],["Average protein on logged days",n.averageProtein,"g"],["Configured protein target",n.proteinTarget,"g"],["Protein adherence days",n.proteinDays],["Average carbohydrates",n.averageCarbs,"g"],["Average fat",n.averageFat,"g"]]}/><p className="text-sm text-muted-foreground">Existing scoring thresholds: calories 85–115% of the configured target; protein at least 85%. Averages use logged dates only. Current targets apply because target history is not stored.</p><ReportChart points={n.calorieTrend} title="Calories logged" unit="kcal"/><ReportChart points={n.proteinTrend} title="Protein logged" unit="g"/></CardContent></Card>
 <Card><CardHeader title="Hydration" description={labels[h.availability]}/><CardContent className="grid gap-5"><Metrics rows={[["Logged days",h.loggedDays],["Average on logged days",h.averageIntake,h.unit],["Configured daily target",h.target,h.unit],["Average target credit on logged days",h.averageTargetPct,"%"],["Days reaching full target",h.targetDays]]}/><p className="text-sm text-muted-foreground">Target credit is capped at 100% per logged day. Extra intake earns no additional adherence credit; missing dates are not treated as known intake.</p><ReportChart points={h.trend} title="Water target credit" unit="%"/></CardContent></Card>
 <Card><CardHeader title="Accountability" description={labels[a.availability]}/><CardContent className="grid gap-5"><Metrics rows={[["Daily habits completed",a.habitCompleted],["Eligible daily habit opportunities",a.habitOpportunities],["Daily habit completion",a.habitPct,"%"],["Daily check-ins",a.checkInDays],["Daily check-in completion",a.checkInPct,"%"],["Weekly check-ins",a.weeklyCheckIns],["Weeks overlapping this range",a.overlappingWeeks],["Check-in streak at period end",a.currentStreak,"days"],["Longest check-in streak in range",a.longestStreak,"days"]]}/><p className="text-sm text-muted-foreground">Streaks are bounded to this range; an unfinished today may continue yesterday’s streak. Daily habits use currently active habits from their local creation date. Weekly habits do not count as daily opportunities.</p><div className="rounded-lg bg-muted p-4"><p className="font-bold">Canonical TFK Score · {a.scoreStart} – {a.scoreEnd}</p>{a.score?<><p className="my-2 text-2xl font-black">{a.score.overall}/100</p><p className="text-sm">Nutrition {a.score.breakdown.nutrition}/30 · Hydration {a.score.breakdown.hydration}/15 · Habits {a.score.breakdown.habits}/30 · Check-ins {a.score.breakdown.checkIns}/15 · Progress {a.score.breakdown.progress}/10</p></>:<p className="text-sm">The complete score is unavailable when a required scoring category is unavailable or not shared.</p>}</div></CardContent></Card>
 <Card><CardHeader title="Training" description={labels[t.availability]}/><CardContent className="grid gap-5"><Metrics rows={[["Scheduled non-archived assignments",t.assigned],["Scheduled assignments completed",t.assignedCompleted],["Assignment completion",t.completionPct,"%"],["Workouts completed during period",t.completed],["Sessions started during period",t.sessions]]}/><p className="text-sm text-muted-foreground">{t.coachScoped?'Only sessions linked to this coach’s assignments in the active relationship are included.':'Completed workouts include self-directed sessions.'} Assignment counts use the scheduled date; workout counts use completion dates. Elapsed session time is not reliable active training duration, so duration is omitted.</p><ReportChart points={t.trend} title="Workout completions" unit="workouts"/></CardContent></Card>
 <p className="text-sm text-muted-foreground">Reports are calculated on demand. GLP-1 records, progress photos and private notes are excluded. No automated interpretations or recommendations are generated.</p>
 </>;
}
