import Link from 'next/link';
import { buttonStyles } from '../../components/ui/button';
import { AppShell } from '../../components/layout/app-shell'; import { Alert } from '../../components/ui/alert'; import { PageHeader } from '../../components/ui/headings'; import { DateNavigation, FoodTools, MealLogs, NutritionSummary, SavedFoods, SavedMeals, WaterSection } from '../../features/nutrition/components'; import { dateInTimeZone, getDailyNutrition } from '../../lib/data/nutrition';
export default async function NutritionPage(
  props:{searchParams: Promise<{date?:string;error?:string;message?:string}>}
) {
  const searchParams = await props.searchParams;
  const data=await getDailyNutrition(searchParams.date);const today=dateInTimeZone(data.profile.timezone);return <AppShell active="nutrition"><div className="grid gap-6"><PageHeader eyebrow="Nutrition" title="What have I eaten today?" description="Log meals and water, then compare daily totals with your plan."/><div className="flex flex-wrap gap-3"><Link href="/nutrition/photo" className={buttonStyles({size:"lg"})}>Log from photo</Link><a href="#manual-food-logging" className={buttonStyles({variant:"outline",size:"lg"})}>Log manually</a></div><DateNavigation date={data.date} today={today}/>{searchParams.error?<Alert variant="error">{searchParams.error}</Alert>:null}{searchParams.message?<Alert variant="success">{searchParams.message}</Alert>:null}<NutritionSummary summary={data.summary} unitsSystem={data.profile.unit_system}/><div id="manual-food-logging"><FoodTools foods={data.foods} recent={data.recentFoods} date={data.date} timezone={data.profile.timezone}/></div><MealLogs logs={data.logs} summary={data.summary} date={data.date} timezone={data.profile.timezone}/><WaterSection logs={data.waterLogs} unitsSystem={data.profile.unit_system} date={data.date} timezone={data.profile.timezone}/><SavedFoods foods={data.foods} date={data.date} timezone={data.profile.timezone}/><SavedMeals savedMeals={data.savedMeals} foods={data.foods} date={data.date} timezone={data.profile.timezone}/></div></AppShell>
}
