/* eslint-disable @next/next/no-img-element */
import type { BodyMeasurement, Milestone, ProgressPhoto, ProgressSummary, UnitSystem, WeightEntry } from '@tfk/types';
import { weightFromKilograms } from '@tfk/validation';
import { SubmitButton } from '../../components/forms/submit-button';
import { Card, CardContent, CardHeader } from '../../components/ui/card';
import { FormField, Input, Select } from '../../components/ui/form';
import { deleteMeasurement, deleteProgressPhoto, deleteWeight, saveMeasurement, saveWeight } from '../../server/actions/progress';
import { PhotoUploadForm } from './photo-upload-form';

const dt = (iso = new Date().toISOString()) => new Date(iso).toISOString().slice(0, 16);
const types = ['waist', 'hips', 'chest', 'neck', 'left_arm', 'right_arm', 'left_thigh', 'right_thigh', 'body_fat'] as const;
const title = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase());
export function SummaryCards({ summary }: { summary: ProgressSummary }) { const stats = [['Current', `${summary.current} ${summary.unit}`], ['Starting', `${summary.starting} ${summary.unit}`], ['Goal', `${summary.goal} ${summary.unit}`], ['Total change', `${summary.change > 0 ? '+' : ''}${summary.change} ${summary.unit}`], ['Remaining', `${summary.remaining} ${summary.unit}`], ['Complete', `${summary.percent}%`], ['Weekly rate', summary.weeklyRate === null ? 'More data needed' : `${summary.weeklyRate} ${summary.unit}/week`], ['Trend', title(summary.trend)]]; return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([name, value]) => <div key={name} className="rounded-xl border bg-card p-4 shadow-card"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{name}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</div>; }
export function WeightChart({ entries, units }: { entries: WeightEntry[]; units: UnitSystem }) { const rows = [...entries].reverse().slice(-12); if (rows.length < 2) return <p className="py-10 text-center text-sm text-muted-foreground">Log at least two weights to see your trend.</p>; const values = rows.map((e) => weightFromKilograms(e.weight_kg, units)); const low = Math.min(...values); const range = Math.max(Math.max(...values) - low, 1); const points = values.map((v, i) => `${10 + i / (values.length - 1) * 80},${85 - (v - low) / range * 65}`).join(' '); return <svg viewBox="0 0 100 100" role="img" aria-label="Recent weight trend" className="h-56 w-full"><line x1="10" y1="85" x2="90" y2="85" className="stroke-border"/><polyline points={points} fill="none" className="stroke-primary" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>; }
export function WeightSection({ entries, units }: { entries: WeightEntry[]; units: UnitSystem }) { const unit = units === 'imperial' ? 'lb' : 'kg'; return <Card><CardHeader title="Weight history" description="Stored canonically in kilograms."/><CardContent className="grid gap-5"><form action={saveWeight} className="grid gap-3 sm:grid-cols-4"><input type="hidden" name="unit_system" value={units}/><FormField id="weight" label={`Weight (${unit})`}><Input id="weight" name="weight" type="number" step="any" min="0.01" required/></FormField><FormField id="weight-date" label="Recorded at"><Input id="weight-date" name="recorded_at" type="datetime-local" defaultValue={dt()} required/></FormField><FormField id="weight-notes" label="Notes"><Input id="weight-notes" name="notes" maxLength={500}/></FormField><SubmitButton className="self-end" pendingLabel="Saving…">Log weight</SubmitButton></form><div className="divide-y rounded-lg border">{entries.length ? entries.map((e) => <details key={e.id} className="p-4"><summary className="cursor-pointer font-semibold">{weightFromKilograms(e.weight_kg, units)} {unit} · {new Date(e.recorded_at).toLocaleString()}</summary><form action={saveWeight} className="mt-3 grid gap-2 sm:grid-cols-4"><input type="hidden" name="id" value={e.id}/><input type="hidden" name="unit_system" value={units}/><Input aria-label="Weight" name="weight" type="number" step="any" min="0.01" defaultValue={weightFromKilograms(e.weight_kg, units)} required/><Input aria-label="Recorded at" name="recorded_at" type="datetime-local" defaultValue={dt(e.recorded_at)} required/><Input aria-label="Notes" name="notes" defaultValue={e.notes ?? ''}/><SubmitButton pendingLabel="Saving…">Save edit</SubmitButton></form><form action={deleteWeight} className="mt-2"><input type="hidden" name="id" value={e.id}/><SubmitButton variant="danger" size="sm" pendingLabel="Deleting…">Delete</SubmitButton></form></details>) : <p className="p-5 text-sm text-muted-foreground">No weight entries yet.</p>}</div></CardContent></Card>; }
export function MeasurementSection({ entries, units }: { entries: BodyMeasurement[]; units: UnitSystem }) { const unit = units === 'imperial' ? 'in' : 'cm'; const shown = (e: BodyMeasurement) => e.measurement_type === 'body_fat' ? e.value : Number((units === 'imperial' ? e.value / 2.54 : e.value).toFixed(2)); return <Card><CardHeader title="Body measurements" description="Lengths use canonical centimeters; body fat uses percent."/><CardContent className="grid gap-5"><form action={saveMeasurement} className="grid gap-3 sm:grid-cols-5"><input type="hidden" name="unit_system" value={units}/><Select aria-label="Measurement" name="measurement_type">{types.map((t) => <option key={t} value={t}>{title(t)}</option>)}</Select><Input aria-label={`Value (${unit} or %)`} name="value" type="number" step="any" min="0" required/><Input aria-label="Recorded at" name="recorded_at" type="datetime-local" defaultValue={dt()} required/><Input aria-label="Notes" name="notes" maxLength={500}/><SubmitButton pendingLabel="Saving…">Log measurement</SubmitButton></form><div className="divide-y rounded-lg border">{entries.length ? entries.map((e) => <details key={e.id} className="p-4"><summary className="cursor-pointer font-semibold">{title(e.measurement_type)}: {shown(e)} {e.measurement_type === 'body_fat' ? '%' : unit}</summary><form action={saveMeasurement} className="mt-3 grid gap-2 sm:grid-cols-5"><input type="hidden" name="id" value={e.id}/><input type="hidden" name="unit_system" value={units}/><Select aria-label="Measurement" name="measurement_type" defaultValue={e.measurement_type}>{types.map((t) => <option key={t}>{t}</option>)}</Select><Input aria-label="Value" name="value" type="number" step="any" min="0" defaultValue={shown(e)} required/><Input aria-label="Recorded at" name="recorded_at" type="datetime-local" defaultValue={dt(e.recorded_at)} required/><Input aria-label="Notes" name="notes" defaultValue={e.notes ?? ''}/><SubmitButton pendingLabel="Saving…">Save edit</SubmitButton></form><form action={deleteMeasurement} className="mt-2"><input type="hidden" name="id" value={e.id}/><SubmitButton variant="danger" size="sm" pendingLabel="Deleting…">Delete</SubmitButton></form></details>) : <p className="p-5 text-sm text-muted-foreground">No measurements yet.</p>}</div></CardContent></Card>; }
export function PhotosSection({ photos, units }: { photos: ProgressPhoto[]; units: UnitSystem }) { return <Card><CardHeader title="Progress photos" description="Private images use one-hour signed URLs."/><CardContent className="grid gap-5"><PhotoUploadForm units={units} defaultRecordedAt={dt()} /><div className="grid gap-4 sm:grid-cols-3">{photos.map((p)=><article key={p.id} className="overflow-hidden rounded-lg border">{p.signed_url ? <img src={p.signed_url} alt={`${title(p.photo_type)} progress`} className="aspect-[4/5] w-full object-cover"/> : null}<div className="p-3"><p className="font-semibold">{title(p.photo_type)}</p><form action={deleteProgressPhoto} className="mt-2"><input type="hidden" name="id" value={p.id}/><SubmitButton variant="danger" size="sm" pendingLabel="Deleting…">Delete photo</SubmitButton></form></div></article>)}{!photos.length ? <p className="text-sm text-muted-foreground">No progress photos yet.</p> : null}</div></CardContent></Card>; }
export function MilestonesSection({ milestones }: { milestones: Milestone[] }) { const all = [['first_weight','First check-in'],['five_weights','Five check-ins'],['goal_reached','Goal reached']] as const; return <Card><CardHeader title="Milestones" description="Deterministic achievements from your progress records."/><CardContent className="grid gap-3 sm:grid-cols-3">{all.map(([type,name])=>{const hit=milestones.find((m)=>m.milestone_type===type);return <div key={type} className={`rounded-lg border p-4 ${hit?'bg-success/5':'bg-muted/40'}`}><p className="font-bold">{name}</p><p className="text-xs text-muted-foreground">{hit?`Earned ${new Date(hit.achieved_at).toLocaleDateString()}`:'Not earned yet'}</p></div>})}</CardContent></Card>; }
