'use client';

import type { GLP1DoseLog, GLP1MedicationProfile, GLP1SymptomLog } from '@tfk/types';
import { useMemo, useState } from 'react';
import { deleteDoseLog, deleteSymptomLog, saveDoseLog, saveMedicationProfile, saveSymptomLog } from '../../server/actions/glp1';
import { Alert } from '../../components/ui/alert';
import { Card, CardContent, CardHeader } from '../../components/ui/card';
import { Input, Select } from '../../components/ui/form';
import { SubmitButton } from '../../components/forms/submit-button';
import { appetiteScale, doseSummary, journalDateTime, localDateTimeInput, medicationLabel, symptomLabel, symptomScale, weekdayLabels } from './domain';

const medications = ['semaglutide','tirzepatide','liraglutide','other'] as const;
const ratings = [1,2,3,4,5] as const;
const symptomKeys = ['nausea','constipation','diarrhea','reflux','fatigue','headache','abdominal_discomfort'] as const;
const title = (value: string) => value.split('_').map((word) => word[0]!.toUpperCase() + word.slice(1)).join(' ');
const hiddenContext = (profileId: string, timezone: string) => <><input type="hidden" name="medication_profile_id" value={profileId}/><input type="hidden" name="timezone" value={timezone}/></>;
const ratingSelect = (name: string, appetite = false) => <Select aria-label={title(name)} name={name} defaultValue=""><option value="">{title(name)} — not recorded</option>{ratings.map((value)=><option key={value} value={value}>{value} · {(appetite ? appetiteScale : symptomScale)[value-1]}</option>)}</Select>;

export function MedicationSetup({ profile }: { profile: GLP1MedicationProfile | null }) {
  const [medication, setMedication] = useState(profile?.medication_name ?? 'semaglutide');
  const [schedule, setSchedule] = useState(profile?.prescribed_schedule ?? '');
  return <Card><CardHeader title={profile ? 'Medication journal profile' : 'Set up GLP-1 journal'} description="Use this journal to record medication you are already taking. TFK does not prescribe medication or recommend dose changes."/><CardContent><form action={saveMedicationProfile} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{profile?<input type="hidden" name="id" value={profile.id}/>:null}<Select aria-label="Medication" name="medication_name" value={medication} onChange={(event)=>setMedication(event.target.value as typeof medication)}>{medications.map((item)=><option key={item} value={item}>{title(item)}</option>)}</Select>{medication==='other'?<Input aria-label="Custom medication name" name="custom_medication_name" defaultValue={profile?.custom_medication_name??''} placeholder="Medication name" required/>:null}<Input aria-label="Started on" name="started_on" type="date" defaultValue={profile?.started_on??''}/><Select aria-label="Prescribed schedule" name="prescribed_schedule" value={schedule} onChange={(event)=>setSchedule(event.target.value as typeof schedule)}><option value="">Schedule (optional)</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="other">Other</option></Select>{schedule==='weekly'?<Select aria-label="Usual day of week" name="usual_day_of_week" defaultValue={profile?.usual_day_of_week??''}><option value="">Usual day (optional)</option>{weekdayLabels.map((day,index)=><option key={day} value={index+1}>{day}</option>)}</Select>:null}<Input aria-label="Usual time" name="usual_time" type="time" defaultValue={profile?.usual_time?.slice(0,5)??''}/><Input aria-label="Profile notes" name="notes" defaultValue={profile?.notes??''} placeholder="Notes (optional)" className="sm:col-span-2"/><SubmitButton pendingLabel={profile?'Updating…':'Saving…'}>{profile?'Update profile':'Save profile'}</SubmitButton></form></CardContent></Card>;
}

function DoseForm({ profile, timezone, now, log }: { profile: GLP1MedicationProfile; timezone: string; now: string; log?: GLP1DoseLog }) {
  const [status,setStatus]=useState(log?.event_type??'taken'); const taken=status==='taken';
  return <form action={saveDoseLog} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{hiddenContext(profile.id,timezone)}{log?<input type="hidden" name="id" value={log.id}/>:null}<Select aria-label="Status" name="event_type" value={status} onChange={(event)=>setStatus(event.target.value as typeof status)}><option value="taken">Taken</option><option value="missed">Missed</option><option value="skipped">Skipped</option></Select>{taken?<><Input aria-label="Dose amount" name="dose_amount" type="number" step="any" min="0.000001" defaultValue={log?.dose_amount??''} placeholder="Dose amount" required/><Select aria-label="Dose unit" name="dose_unit" defaultValue={log?.dose_unit??''} required><option value="">Unit</option><option value="mg">mg</option><option value="mcg">mcg</option><option value="units">units</option><option value="other">other</option></Select><Select aria-label="Injection site" name="injection_site" defaultValue={log?.injection_site??''}><option value="">Site (optional)</option><option value="abdomen">Abdomen</option><option value="thigh">Thigh</option><option value="upper_arm">Upper arm</option><option value="other">Other</option><option value="not_applicable">Not applicable</option></Select></>:null}<Input aria-label="Date and time" name="taken_at" type="datetime-local" defaultValue={log?localDateTimeInput(log.taken_at,timezone):localDateTimeInput(now,timezone)} required/><Input aria-label="Medication notes" name="notes" defaultValue={log?.notes??''} placeholder="Notes (optional)" className="sm:col-span-2"/><SubmitButton pendingLabel={log?'Updating…':'Saving…'}>{log?'Update entry':'Save entry'}</SubmitButton></form>;
}

export function MedicationLogging({ profile, timezone, now, logs }: { profile: GLP1MedicationProfile; timezone: string; now: string; logs: GLP1DoseLog[] }) {
  return <Card><CardHeader title="Log medication" description="Record what you took—or note a missed or skipped entry. Dose is never prefilled."/><CardContent className="grid gap-5"><DoseForm profile={profile} timezone={timezone} now={now}/>{logs.length?<details><summary className="cursor-pointer text-sm font-semibold text-primary">Edit a recent entry</summary><div className="mt-4 grid gap-4">{logs.slice(0,10).map((log)=><div key={log.id} className="rounded-lg border p-4"><p className="mb-3 text-sm font-semibold">{journalDateTime(log.taken_at,timezone)} · {doseSummary(log)}</p><DoseForm profile={profile} timezone={timezone} now={now} log={log}/><form action={deleteDoseLog} className="mt-2"><input type="hidden" name="id" value={log.id}/><SubmitButton variant="danger" size="sm" pendingLabel="Deleting…">Delete</SubmitButton></form></div>)}</div></details>:null}</CardContent></Card>;
}

export function SymptomLogging({ profile, timezone, now, doses }: { profile: GLP1MedicationProfile; timezone: string; now: string; doses: GLP1DoseLog[] }) {
  return <Card><CardHeader title="Symptom journal" description="Record intensity only. These entries do not assess medical risk or establish that medication caused a symptom."/><CardContent className="grid gap-4"><Alert>If you are concerned about symptoms or they are severe or persistent, contact a healthcare professional.</Alert><form action={saveSymptomLog} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{hiddenContext(profile.id,timezone)}<Input aria-label="Logged at" name="logged_at" type="datetime-local" defaultValue={localDateTimeInput(now,timezone)} required/><Select aria-label="Related medication entry" name="dose_log_id" defaultValue={doses[0]?.id??''}><option value="">No linked dose</option>{doses.slice(0,10).map((dose)=><option key={dose.id} value={dose.id}>{journalDateTime(dose.taken_at,timezone)} · {doseSummary(dose)}</option>)}</Select>{ratingSelect('appetite',true)}{ratingSelect('hunger',true)}{symptomKeys.map((key)=><span key={key}>{ratingSelect(key)}</span>)}<Input aria-label="Other symptoms" name="other_symptoms" placeholder="Other symptoms"/><Input aria-label="Symptom notes" name="notes" placeholder="Notes (optional)"/><SubmitButton pendingLabel="Saving…">Save symptom entry</SubmitButton></form></CardContent></Card>;
}

export function JournalHistory({ profile, timezone, doses, symptoms }: { profile: GLP1MedicationProfile; timezone: string; doses: GLP1DoseLog[]; symptoms: GLP1SymptomLog[] }) {
  const [range,setRange]=useState('30'); const [trend,setTrend]=useState<'nausea'|'appetite'|'hunger'|'fatigue'>('nausea');
  const cutoff=range==='all'?0:Date.now()-Number(range)*86400000; const visibleDoses=doses.filter((log)=>new Date(log.taken_at).getTime()>=cutoff);
  const trendPoints=useMemo(()=>symptoms.filter((log)=>log[trend]!=null).slice().reverse(),[symptoms,trend]);
  return <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader title="Dose timeline" description="A chronological record of user-entered medication events."/><CardContent><Select aria-label="Timeline range" value={range} onChange={(event)=>setRange(event.target.value)} className="mb-4 max-w-40"><option value="30">30 days</option><option value="90">90 days</option><option value="all">All</option></Select><ol className="grid gap-3">{visibleDoses.map((log)=><li key={log.id} className="border-l-2 border-primary/30 pl-4 text-sm"><p className="font-bold">{journalDateTime(log.taken_at,timezone)} · {title(log.event_type)}</p><p className="text-muted-foreground">{medicationLabel(profile)} · {doseSummary(log)}{log.injection_site?` · ${title(log.injection_site)}`:''}</p>{log.notes?<p>{log.notes}</p>:null}</li>)}{!visibleDoses.length?<li className="text-sm text-muted-foreground">No medication entries in this range.</li>:null}</ol></CardContent></Card><Card><CardHeader title="Recorded symptom trend" description="Recorded intensity over time; this view does not imply causation."/><CardContent><Select aria-label="Trend symptom" value={trend} onChange={(event)=>setTrend(event.target.value as typeof trend)} className="mb-4"><option value="nausea">Nausea</option><option value="appetite">Appetite</option><option value="hunger">Hunger</option><option value="fatigue">Fatigue</option></Select><div className="flex min-h-36 items-end gap-2 border-b border-l p-3">{trendPoints.slice(-20).map((log)=><div key={log.id} className="group flex min-w-3 flex-1 items-end" title={`${journalDateTime(log.logged_at,timezone)}: ${log[trend]}`}><span className="w-full rounded-t bg-primary/70" style={{height:`${Number(log[trend])*20}%`}}/></div>)}</div><p className="mt-2 text-xs text-muted-foreground">Scale: 1–5. Appetite and hunger run very low to very high; symptoms run none/minimal to severe.</p></CardContent></Card><Card className="xl:col-span-2"><CardHeader title="Recent symptom history" description="The latest 50 entries."/><CardContent className="grid gap-3">{symptoms.map((log)=><div key={log.id} className="rounded-lg border p-3 text-sm"><p className="font-bold">{journalDateTime(log.logged_at,timezone)}</p><p className="text-muted-foreground">Appetite: {symptomLabel(log.appetite,true)} · Hunger: {symptomLabel(log.hunger,true)}</p><p className="text-muted-foreground">Nausea: {symptomLabel(log.nausea)} · Fatigue: {symptomLabel(log.fatigue)} · Abdominal discomfort: {symptomLabel(log.abdominal_discomfort)}</p>{log.other_symptoms?<p>{log.other_symptoms}</p>:null}<form action={deleteSymptomLog} className="mt-2"><input type="hidden" name="id" value={log.id}/><SubmitButton variant="danger" size="sm" pendingLabel="Deleting…">Delete</SubmitButton></form></div>)}{!symptoms.length?<p className="text-sm text-muted-foreground">No symptom entries yet.</p>:null}</CardContent></Card></div>;
}
